// <auto-generated />
namespace ConsoleApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208142324590_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/sI2rbVGV+vFqVxTRrCZ3dj9LjssgIldd5ef6eeO08BF4f2R6pz1PCrb1+c73Kud/PPnpJw66Wfhtq9Xvl18EH9NHLulrldXv9Kj8P3jybfZTeDd++233dvtx7E4h89tHZsr2391H6Yl2W2aSkD86zssk/SlefPnrdVnX+eb7M66zNZy+zts1rmqOzWc4DUYI8Wn16O5o8vLuzB5rczZbLqmUK99DvIPs8a1r8ZpB93dbEPx+lz4p3+ex5vrxo5xbhL7J35hP69aP0q2VB7EYvtfU69wcof2/u+FlR/xz1/KSo2/lTIrjpGb+/KYBJb458SI/vOvbazHR19dP5tP1aXCevfi22c6/+f4Dvfk5m/otsmV3k9c0k6oB5kV0WFzysOMCP0ld5yd8382Ilymys8/H72zbP6mrxqkIvna9+/9fVup6CHFX8+zdZfZG3t+PG46appgUjEzKGRSQc2+lylt6AlUySNyaalnXZFlDjhMFnH32rR7FhqGYsPlRR0h2guyGiBPTL5dO8zNs8PZ62bMtOsmaazfrzRaSZhZ+QhOU1mDsrYYXaOiuWbV8ci+W0WGXlZtQ7r72X9QBytpvuN0/zVb6ECG6ekNv073F6HwHbT4dqNxHp8V2PufoakN5p6Y28NjjwJ/m7riKU1q/zNqBV81HqGLrDGD3m6gAQOkUhGIbtgPAG0oPjJNZrNSDUXdreLE0WeR/v3hzdLD8+HEPArhiEo4woDztl9rvHd8Vv0w8e3x1w8B5/ka1WpLU9h08/SV+rt7f9+v0duoXAuDttIn6dxdb2RGaMiNL5Fo7mLGf/gix7Nsmg0U9mi16zGxnU9BPyaX+uDNOZ9vhd3om4vIar+2Ksrz+jMS2gBdhK9+a5/2IKZzsrs3rQET2pyvVieZNqGobkvEQfkvv09pA8t88H5X18e1ieI+fD8j7uw3p8t0PlnnbsTWfPtoTccTveMaL+wcwT8y0Z0o3cM/TmIPs4hzLgnyEXdROs/oy/72R7Fs0Hs8HQ/SxPdk+HdpvY3q0u7ejMx6q/AsXK4+9Hzh2FJk0+SolIl8UMyuz1ddPmizEajF//ovKkLGi8rgHRqTjPm/ZN9TZHFoD07dePva2/3zSz8v/9AXgBQtwY8twUBAyqROlkeZnV03lWby2yd3feNzDpBcMfBK0X4M7odyRt/n8W4P6szOs3Ngu9YJPR/VoT8AExnXrQP9xoq+e9fr0g8usFbUPe1e01DMb0vkHarTr8f0NU1veNu3MXi842BGdiikjJTCqaZuHtl3m1Kvuc0oNtOKEP3HwThT4QN/0worqAGr5XfosYLhb8fb2g7aagre9YEB+tlzZxT1zcFBcOBNL4y5zl3AE1bc6W55Xh5U4YaZp0VV/eZmRzsuO6Lc6zaUtfT/Om4STfT2blmpqcLib57Gz55bpdrVuakXwxKa99YkAgNvXPkWmI8+MvV5yD+yaGQGgWMJtfLp+si3Jm8X4W0doDICBpapjAkC0M1MW1hfSiWt4SkJLvqVEQb/LFitKNefPl8nV2mQ/jdjMNQ4o9flpkF3W28Ckonygmr7NFINfUgf+G64/+JLtAq0ZH/08AAAD///Lrdj2qGgAA"; }
        }
    }
}
